# Generated by Django 4.2.7 on 2025-05-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='amount_paid',
        ),
    ]
