# Generated by Django 4.2.7 on 2025-05-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_remove_feerecord_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='fees_qr/')),
                ('account_number', models.CharField(blank=True, max_length=32)),
                ('ifsc_code', models.CharField(blank=True, max_length=16)),
                ('upi_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
