# Generated by Django 4.2.7 on 2025-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
