# Generated by Django 4.2.7 on 2025-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_feepayment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
