# Generated by Django 4.2.7 on 2025-05-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0002_alter_outing_approved_by_outingrequest'),
        ('fees', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='outing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outings.outingrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('outing_requested', 'Outing Requested'), ('outing_approved', 'Outing Approved'), ('outing_rejected', 'Outing Rejected')], max_length=20),
        ),
    ]
