# Generated by Django 4.2.7 on 2025-05-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0002_alter_outing_approved_by_outingrequest'),
        ('fees', '0009_notification_outing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='outing_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outings.outingrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='outing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outings.outing'),
        ),
    ]
