# Generated by Django 5.1.6 on 2025-06-15 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('outing_requested', 'Outing Requested'), ('outing_approved', 'Outing Approved'), ('outing_rejected', 'Outing Rejected'), ('custom', 'Custom Notification')], max_length=20),
        ),
    ]
