# Generated by Django 4.2.30 on 2026-04-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_notification_created_by_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='outing_request',
        ),
    ]
