# Generated by Django 4.2.7 on 2025-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0002_alter_outing_approved_by_outingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent Email'),
        ),
    ]
