# Generated by Django 4.2.30 on 2026-04-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_remove_notification_outing_request'),
        ('outings', '0003_outing_parent_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutingRequest',
        ),
    ]
